specPattern:
  - cypress/e2e/pages/login.cy.js
  - cypress/e2e/pages/base/header.cy.js
  - cypress/e2e/pages/cluster/registry.cy.js
  - cypress/e2e/pages/region/region.cy.js
  - cypress/e2e/pages/access/oauth2.cy.js
  - cypress/e2e/pages/access/platform-user-role.cy.js
