specPattern:
  - cypress/e2e/pages/node/node.cy.js
  - cypress/e2e/pages/cluster/cluster.cy.js
  - cypress/e2e/pages/cluster/template.cy.js
  - cypress/e2e/pages/cluster/hosting-kubeadm.cy.js
  - cypress/e2e/pages/cluster/backup.cy.js
