name: full-front-e2e-test
on:
  push:
    branches:
      - 'master'
      - 'release*'
      

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  
  Pre:
    name: Prepare
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CHJ_REMOTE_HOST }}
          username: root
          key: ${{ secrets.CHJ_REMOTE_KEY }}
          port: ${{ secrets.CHJ_REMOTE_PORT }}
          script: |
            rm -rf /root/console

      - name: Copy
        uses: appleboy/scp-action@master
        env: 
          HOST: ${{ secrets.CHJ_REMOTE_HOST }}
          USERNAME: root
          PORT: ${{ secrets.CHJ_REMOTE_PORT }}
          KEY: ${{ secrets.CHJ_REMOTE_KEY }}
        with:
          source: "/home/runner/work/console/console"
          target: "/root/console"

  Deploy:
    name: Deploy and Run e2e
    runs-on: ubuntu-latest

    steps:

      - name: Get branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 60m
          host: ${{ secrets.CHJ_REMOTE_HOST }}
          username: root
          key: ${{ secrets.CHJ_REMOTE_KEY }}
          port: ${{ secrets.CHJ_REMOTE_PORT }}
          script: |
            set -e
            sh /root/deploy-${{ steps.extract_branch.outputs.branch }}.sh

      - name: Run e2e
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 120m
          host: ${{ secrets.CHJ_REMOTE_HOST }}
          username: root
          key: ${{ secrets.CHJ_REMOTE_KEY }}
          port: ${{ secrets.CHJ_REMOTE_PORT }}
          script: |
            set -e
            pushd /root/console/github/workspace
            yarn config set registry https://registry.npm.taobao.org/
            yarn install
            sed -i "s/localhost/172.20.139.233/" cypress/config/config.yaml
            sh tools/e2e-smoke.sh
            ssh root@172.16.30.27 "mkdir -pv /var/www/html/caas-test-case/github/${{ steps.extract_branch.outputs.branch }}"
            scp testcases-cases.html root@172.16.30.27:/var/www/html/caas-test-case/github/${{ steps.extract_branch.outputs.branch }}/
            scp testcases-e2e-summary.html root@172.16.30.27:/var/www/html/caas-test-case/github/${{ steps.extract_branch.outputs.branch }}/
            scp cypress/report/merge-report.html root@172.16.30.27:/var/www/html/caas-test-case/github/${{ steps.extract_branch.outputs.branch }}/
            scp cypress/report/merge-report.json root@172.16.30.27:/var/www/html/caas-test-case/github/${{ steps.extract_branch.outputs.branch }}/
            ssh root@172.16.30.27 "rm -rf /var/www/html/caas-test-case/github/${{ steps.extract_branch.outputs.branch }}/assets"
            scp -r cypress/report/assets root@172.16.30.27:/var/www/html/caas-test-case/github/${{ steps.extract_branch.outputs.branch }}/
            if [ -d "cypress/screenshots" ];then
            ssh root@172.16.30.27 "rm -rf /var/www/html/caas-test-case/github/${{ steps.extract_branch.outputs.branch }}/screenshots"
            scp -r cypress/screenshots root@172.16.30.27:/var/www/html/caas-test-case/github/${{ steps.extract_branch.outputs.branch }}/
            echo e2e-test fail
            exit 110
            else
            echo e2e-test successfully
            fi
